const lists = [
"4BAGS NATALIA WEDRAL",
"A.T GROUP Sp.z o.o.",
"AB LINAS AGRO; (Smelynes 2c, PANEVEZYS(Poniewież) 35143, LT)",
"ADAM KLOC FHU; (Genowefa 37a, 62 - 513 KRZYMÓW, PL)",
"AGENCJA OCHRONY "VIP GUARD" Sp.z o.o.",
"AGERONA Sp.z o.o.",
"AGICORP Sp.z o.o.",
"AGRAVIS OST GMBH & amp;CO KG; (Haupstr.100, BULSTRINGEN 39345, DE)",
"AGRIFEED SP.Z O.O.; (Partyzantów 57, 22 - 400 ZAMOŚĆ, PL)",
"AGRIKAM Sylwia Krawczyk Firma Handlowa; (KRZEPCZÓW NOWY 16A, GRABICA 50 97 - 306, PL)",
"AGRIKO DERENDARZ MICHAŁ; (Szydłów Kolonia 49, 97 - 306 GRABICA, PL)",
"AGRISTOCK SP Z O.O.; (Wola Rogozińska 5, 95-001 BIAŁA, PL)",
"AGRO - BUSINESS TRADE SP.Z.O.O; (MIESZKOWO 10, MASZEWO 72 - 130, PL)",
"AGRO - DUK KRYSTIAN DUK",
"AGRO - ENERGIA Andrzej Wawrzyniak; (Kruszyna 14, 76 - 251 KOBYLNICA, PL)",
"AGRO - INTER Sp.z o.o.",
"AGRO - MAR FIRMA HANDLOWA; (Grabica 38, 97 - 306 GRABICA, PL)",
"Agro - Mursy Łukasz Tomczuk",
"AGRO - TRADE Karol Pieczko",
"AGRO - UPOL Sp.z o.o.; (Nowa 100, 22 - 500 HRUBIESZÓW, PL)",
"AGRO - V POLSKA, UL.SĄDOWA 8 / 1, 20-027 LUBLIN",
"AGROCENTRUM SP.Z O.O.; (Kolejowa 1, 18 - 500 KOLNO, PL)",
"AGRO EXPRES Sp.z o.o.",
"AGRO INTERNATIONAL Sp.z o.o",
"AGROKOMPAKT ŁUKASZ GORBACZ; (Jeziorowskie 40, 11 - 612 KRUKLANKI, PL)",
"AGROL ARTUR JARZĘBOWSKI; (Grabica 50, 97 - 306 GRABICA 50, PL)",
"AGROLOG SP.Z O.O.; (Dowborczyków 30 / 34, 90 -019 ŁÓDŹ, PL)",
"AGROLOG Sp Z O O; (Gęsia 8 / 205, 31 - 535 KRAKÓW, PL)",
"AGROLOK SP.Z O.O.; (Dworcowa 4, 87 - 400 GOLUB - DOBRZYŃ, PL)",
"AGRONEX SP.Z.O.O.; (Tylna 11, 95 -080 MĄKOSZYN, PL)",
"AGROOILTRADE OU",
"AGROS Sylwia Samek F.H.U; (Młodzawy Duże, 28 - 400 PIŃCZÓW, PL)",
"AGRO TORG; (Dowborczyków, 90 -019 ŁÓDŹ(ŁÓDŹ - ŚRÓDMIEŚCIE), PL)",
"AGROTORG SP.Z O.O.; (Dowborczyków 30 / 34, 90 -019 ŁÓDŹ, PL)",
"AGROTRADE Sp.z o.o.; (Juliana Smulikowskiego 4a Lok. 16., 00 - 389 Warszawa, PL)",
"AGSOL SP.J.ZDZISŁAW WRÓBEL I AGNIESZKA WIELGUS; (Wójczańska 17, 28 - 133 PACANÓW, PL)",
"ALBIO Sp.z o.o.; (Ul.Ogrodowa 1 Piski, 07 - 407 CZERWIN, PL)",
"Aleksandra Pietrzak Firma Handlowo - Usługowa "OL-WI"",
"AMB POLSKA SP.Z O.O.; (Kaliska 11a, 63 - 410 CZEKANÓW, PL)",
"AMEX AGNIESZKA MAJ(Piskorka)",
"AMF LIFE MATEUSZ WRÓBEL; (Wola Rzędzińska 410D, 33 - 150 WOLA RZĘDZIŃSKA, PL)",
"AMPOL MEROL SP.Z O.O.; (Mikołaja z Ryńska 28 A, 87 - 200 WĄBRZEŹNO, PL)",
"ANAKUS Sp.z o.o.; (Sidorska 54 Lok. 20a, 21 - 500 Biała Podlaska, PL)",
"Aquael Sp.zo.o.Warszawa",
"ARPPM SP.Z.O.O.; (UL.WERNERA 33 / 37, RADOM 26 - 600, PL)",
"ATLAS TRADING SP ZOO; (Ul.Budowlana 6, 20 - 469 LUBLIN, PL)",
"Basis Development Sp.z o.o.",
"BENTYNKI BOGDAN BENTYN; (Pocztowa 9, 62 - 200 GNIEZNO, PL)",
"BIMEO 1 SP.Z.O.O; (UL.ZŁOTA 75 A / 7, WARSZAWA 00 - 819, PL)",
"BIMEO 1 SP.Z O.O.; (Plac Stanisława Małachowskiego 2, 00-066 WARSZAWA, PL)",
"BIO - GRAIN SP.Z O.O.; (Ul.Wólczyńska 133, 01 - 919 WARSZAWA, PL)",
"BMdrog Sp.z o.o.",
"BN - POL SP ZOO; (Ks.Jana Kompałły 3a / 2, 63 - 400 OSTRÓW WIELKOPOLSKI, PL)",
"BOŻEK SKŁAD SP.Z O.O.; (Teptiuków 58, 22 - 500 HRUBIESZÓW, PL)",
"BOŻEK SKŁAD SZYMON BOŻEK; (Teptiuków 59, 22 - 500 HRUBIESZÓW, PL)",
"BROMEX Sp.z o.o.",
"BUDEXIM SP.Z O.O.; (Jedności Narodowej 55 - 57 / 7, 50 - 262 WROCŁAW, PL)",
"BUJAKOWSKI ANTONI HANDEL OBWOŹNY ARTYKUŁAMI SPOŻYWCZO - ROLNYMI; PL1010112p(Żądło 22, 97 - 306 GRABICA, PL)",
"BUMERANG - TRANS BARTOSZ; (WIATRAKOWA 3, ŚMIGIEL 64-030, PL)",
"BUNGE POLSKA SP.Z O.O.; (Niepodległości 42, 88 - 150 KRUSZWICA, PL)",
"BZK GROUP SP.Z O.O.; (Połczyńska 97 A, 01 - 303 WARSZAWA, PL)",
"CAPITAL TRADE SP.Z O.O.; (Ogrodowa 58, 00 - 876 WARSZAWA, PL)",
"CARGILL Poland Sp.z o.o.; (Wołoska 22, 02 - 675 WARSZAWA, PL)",
"CEDROB S.A.; (Ujazdówek 2 A, 06 - 400 CIECHANÓW, PL)",
"CHEMIROL Sp.zo.o.P.U.H.; (Przemysłowa 3, 88 - 300 MOGILNO, PL)",
"CL INVESTMENTS SP ZOO; (FRYDERYKA CHOPINA41 / 2, LUBLIN 20-023, PL)",
"CONECTO LOGISTICS SP.Z O.O.; (Przemysłowa 39, 61 - 541 POZNAŃ, PL)",
"CORN TRANS GROUP Sp.z o.o.; (Partyzantów 57, 22 - 400 Zamość, PL)",
"CORN TRANS Sp.z o.o.Sp.K.",
"Crisp Malt Sp.z o.o. (dawniej: GlobalMalt Polska Sp.z o.o.)",
"CROPFIELD TRADING COMPANY OU",
"DACSA Polska Sp.z o.o.",
"DAKU International Sp.z o.o.; (Ludwika Idzikowskiego 16, 00 - 710 WARSZAWA(MOKOTÓW), PL)",
"DAKU International Sp.z o.o.; (Okrężna 83, 02 - 933 WARSZAWA, PL)",
"DE HEUS SP.Z O.O.; (Lotnicza 21 B, 99 - 100 ŁĘCZYCA, PL)",
"DIGITEX Sp.z o.o.Sp.k.",
"DK AGRO TRADE Dariusz Kornik",
"DM COMODITIES; (Al.Stanów Zjednoczinych 15 / 421, 04 -028 WARSZAWA, PL)",
"Dried Fruits Sp.z o.o.",
"DRIED FRUITS SP.Z O.O.; (OLIMPIJSKA 24, SIEMIANOWICE ŚLĄSKIE 41 - 100, PL)",
"DWA PLUS SP.Z O.O.; (Oś.Królewska 18lok / U01, 02 - 972 WARSZAWA, PL)",
"DWT Sp.z O.O; (Rojów, Hetmańska 10, z siedzibą firmy ul.Hetmańska 10, 63 - 500 Ostrzeszów, PL)",
"ECCO KPO; (Okulickiego 7 / 2, 26 - 600 RADOM, PL)",
"ECG Seeds Sp.z o.o., Długa 16, 85-031 Bydgoszcz, Polska",
"ECOMAC Sp.zo.o. Bielsko biała",
"ECOMASTER Sp.z o.o.",
"EKO - DOM S.Z O.O.; (Uniszki - cegielnia 23a, 06 - 500 MŁAWA, PL)",
"EKO GK GABRIELA NIESŁUCHOWSKA; (Mazowiecka 83, 05 - 255 STARE ZAŁUBICE, PL)",
"EKOGRAIN ROBERT PRUS FHU",
"ELEWATOR SIERADZ SP.Z O.O.; (Elewatorska 1, 98 - 200 SIERADZ, PL)",
"ELIT - TRANS BOŻENA BOGACZ; (DMENIN 146, KODRĄB 97 - 512, PL)",
"ELPOLOGISTYKA SP.Z O.O.; (Zawada 26, 28 - 230 POŁANIEC, PL)",
"ELPOL ŁUŹNIAK SPÓŁKA KOMANDYTOWA; (Osina Mała 14, 98 - 358 KIEŁCZYGŁÓW, PL)",
"Emilia Kosovets H.P.U.MIREM EXPORT - IMPORT",
"EMIMAR KRYSTYNA OPONOWICZ; (Wagowa 68 / 21, 41 - 215 SOSNOWIEC, PL)",
"EMIX OIL SP.Z O.O.; (Świątkowice 61 A, 98 - 360 LUTUTÓW, PL)",
"ENERGOSTROJ Sp.z o.o.",
"ENERGY MARIUSZ ZIELIŃSKI; (1, KĄKOLNO 55 - 140, PL)",
"ENSPED SPÓŁKA Z.O.O.; (Dworcowa 4 B, 22 - 500 Hrubieszów, PL)",
"EPARTS Sp z o.o.; (Aleja Jana Pawła II 27, WARSZAWA 00 - 867, PL)",
"ERIDON Sp.z O.O., Dantyszka 18, 01-054 Warszawa",
"ERIDON SP.Z O.O.; (Jana Dantyszka 18, 02-054 WARSZAWA, PL)",
"Etmos Sp.z o.o.Sp.K.",
"EURO AGRO; (Strzebielinko 1a, 84 - 250 GNIEWINO, PL)",
"EUROPIAN MING AND ENERGY GROUP OU; (Paszowice 52b, 59 - 411 PASZOWICE, PL)",
"Eurowinpol Sp.z o.o.",
"EVERWELLE OSAUHING",
"EXIMCOMPANY OU",
"Eximcompany OU Tallinn",
"F.H.U.KAMA AGATA KMIECIK",
"F.H.U.P.ROMADO MARIA SZCZEPAŃSKA",
"F.H.U.TOMASZ GRUNT",
"F.H.U.ZUZA ZUZANNA GIEC; (UL.ŚW PAWŁA ii 53, ZALESZANY 37 - 415, PL)",
"FEEDOIL Sp.z.o.o.; (Dworcowa 15, 73 - 120 CHOCIWEL, PL)",
"FEEDSTAR Sp.z O.O.; (Królewska 6, 05 - 825 GRODZISK MAZOWIECKI, PL)",
"FERMA DROBIU WOŹNIAK SP.Z O.O.; (ŻYLICE 35A, RAWICZ 63 - 900, PL)",
"FHU KALINOWSKI Tomasz Kalinowski",
"FHU KARP JACEK; (Dąbrowa 1c, 97 - 217 LUBOCHNIA, PL)",
"FHU OL - WI; (ZA JEZIOREM 13, Sławno 62 - 265, PL)",
"Firma " ZWIREK", Nowa Wieś Zbaska 61, 64 - 360 Zbąszyń, Polska",
"Firma EMIMAR Krystyna Oponowicz; (Wagowa 68 / 21, 41 - 215 SOSNOWIEC, PL)",
"FIRMA HANDLOWA RAFAŁ KARP",
"FIRMA PRODREW, KRZYSZTOF TOMASZ, KOPERNIKA 25A, 14 - 310 Miłakowo, Polska",
"FIRMA USŁUGOWO - HANDLOWA DARIUSZ BŁOŃSKI",
"FITCOM FITAŁ KRZYSZTOF P.H.U.; (A.Gromskiego 2 / 62, 35 - 233 RZESZÓW, PL)",
"FODER BIO - TECH Sp.z o.o.; (Bitwy Warszawskiej 1920 21 / 93, 02 - 366 WARSZAWA, PL)",
"FOOD TRADE Sp.z o.o.",
"FORPOST Sp.z o.o.; (Ul.Mełgiewska 74 / 200, 20 - 234 Lublin, PL)",
"FORTIS LOGISTICS GROUP Sp.z o.o.",
"FPT SP.Z O.O.; (Bysewska 30, 80 - 298 GDAŃSK, PL)",
"FREEZEPOINT SP.Z O.O.Oddział Tomaszów Lubelski; (Rolnicza 10, 22 - 600 Tomaszów Lubelski, PL)",
"FRESChO Group Poland Sp.z o.o.",
"Fruges Trade Sp.z o.o.",
"GAB PPHU SP.Z O.O.; (Olmonty 20, 15 - 603 OLMONTY, PL)",
"GALAGROTRADE SP.Z O.O.; (Al.Komisji Edukacji Narodowej 36 / 112b, 02 - 797 WARSZAWA, PL)",
"GARANT LLB Sp.z o.o.",
"GINTER AGRO Sp.z o.o.",
"GINTER TRADE Sp.z o.o.",
"GLOBAL GO Sp.z o.o.",
"GOREX SP.Z O.O.; (MONIUSZKI 42, GORZÓW WIELKOPOLSKI 66 - 400, PL)",
"GORZOWSKIE TOWARZYSTWO HANDLU ZAGRANICZNEGO GOREX SP.Z O.O.; (Moniuszki 42, 66 - 400 GORZÓW WIELKOPOLSKI, PL)",
"GOSPODARSTWO ROLNE FERMA DROBIU KATARZYNA KOTUS; (Witów 3 A, 99 - 120 PIĄTEK, PL)",
"GOZAC SP.Z.O.O.; (Młyńska 5 / 9, 61 - 729 POZNAŃ, PL)",
"GP Buraka Cukrowego Dobra Sp.z o.o.",
"GRAINFORCE Sp.z o.o.",
"GRAINFOR TRADE LTD; (18 / 2 South Street, VALETTA 1102, MT)",
"GRAIN Sp.z o.o.",
"GRUNWEG PL Sp.z o.o.; (Szańcowa 44, 01 - 458 WARSZAWA, PL)",
"GRUPA AGROCENTRUM SP.Z O.O.; (Al.Legionów 135a, 18 - 400 ŁOMŻA, PL)",
"GRUPA AWW Sp.z o.o.",
"GRUPA PRODUCENTÓW BURAKA CUKROWEGO "DOBRA" Sp.z o.o",
"GRUSZKA RADOSŁAW OWOCE WARZYWA; (Będziaki 50, 28 - 506 CZARNOCIN, PL)",
"GRZEGORZ FILIPOWSKI, RESTAURACJA,, SMAKI ŚWIATA’’",
"H.P.U.Mirem Export - Import Gryfice",
"HANDEL ART.ROLNYMI TRANSPORT WIESŁAW MUZYKA",
"HS FARM SP.Z O.O.; (SITANIEC - WOLICA 216, ZAMOŚĆ 22 - 400, PL)",
"IGS COMMODITY S.R.O.",
"IMA POLSKA S.A; (Ul.Polna 21, 62 -095 MUROWANA GOŚLINA, PL)",
"IMARTI POLAND SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA",
"IMA UL.KATOWICKA 79A / 101 61 - 131 POZNAŃ; (Polna 21, 62 -095 MUROWANA GOŚLINA, PL)",
"INFAVOR Sp.z o.o.",
"INGLIA SP.ZO.O.; (Okopowa 8, 20-022 LUBLIN, PL)",
"INT DARIUSZ KOTARA; (Mickiewicza 6 / 21, 28 - 200 STASZÓW, PL)",
"INTERMARKET Sp.z o.o.",
"INTERNATIONAL LOGISTIC SP.Z O.O.; (Konopnica 97a, 21-030 MOTYCZ, PL)",
"Jacek Karp Firma Handlowo Usługowa "KARP"",
"JAKPOL Jakub Ambroziak; (Szosa Ciechanowska 24, 06 - 420 Gołymin - Ośrodek, PL)",
"JAPP SP.Z O.O.; (Św.Michała 43, 61 - 119 POZNAŃ, PL)",
"JULTIM PPHU JULIA MIELCZAREK; (Wieluńska 12 A, 97 - 438 RUSIEC, PL)",
"JUSTAL AGRO SP.Z O.O.; (Ul.Rogatka 3 / 1, 31 - 425 KRAKÓW, PL)",
"KAMPOL P.P.H.U KRZYSZTOF ŁUŹNIAK; (Wieluńska 12 A, 97 - 438 RUSIEC, PL)",
"KARP FHU JACEK KARP; (Dąbrowa 1c, 97 - 217 LUBOCHNIA, PL)",
"KARP RAFAŁ FIRMA HANDLOWA; (Dąbrowa 2, 97 - 217 LUBOCHNIA, PL)",
"Kaszpol Agro Grzegorz Ziółkowski",
"KG Polska Sp.z o.o.; (Sejneńska 51, 16 - 400 SUWAŁKI, PL)",
"Komagra Sp. z o.o. +52 302 40 03",
"KORCZOWA; (Przejście Graniczne W Korczowej, 37 - 550 RADYMNO, PL)",
"KORM SŁAWOMIR BĘDKOWSKI; (Staffa 2, 41 - 215 SOSNOWIEC, PL)",
"KRYSPOL EXPORT - IMPORT Krystyna Wołoszyn; (Obojna 74, 37 - 415 ZALESZANY, PL)",
"Krzysztof Borek Zakład Produkcyjno - Usługowo - Handlowy "BAK-ROL"",
"KUR - PASZ DANIEL KURDYK; (Beznatka 4, 62 - 834 CEKÓW, PL)",
"KWS LOCHOW POLSKA SP Z O.O., SLOWIANSKA 5, 57 - 150 Kondratowice, Polska",
"KWS POLSKA SP Z.O.O., UL.CHLEBOWA 4 / 8, 60 - 734 Poznań, Polska",
"L'HOM Designs Robert Bieńkowski",
"LAUNTOP POLSKA CEZARY PODSIADŁO; aPL3010003p(Lubomyśle 1b, 62 - 561 ŚLESIN, PL)",
"LECHPOL PW SP.Z O.O.; (Jana Pawała Ii 36, 89 - 200 SZUBIN, PL)",
"LEMBERGS SP.ZO.O.; (UL.NAPĘDOWA 1, Milejowice 26 - 652, PL)",
"LEVEL - SC(Warszawa)",
"LEWANDOWSKI TOMASZ Firma Usługowo Budowlana; (Wiatrakowa 1b, 64-030 ŚMIGIEL, PL)",
"Lidea Poland(Poznań)",
"Lidea Poland sp.z o.o, Wichrowa 1 a, 61 - 189 Poznań, Polska",
"Lider Polska Sp z o.o.; (Al.Józefa Mireckiego 22, 41 - 200 Sosnowiec, PL)",
"LINAS AGRO AB; (Smelynes 2c, PANEVEZYS LT - 35143, LT)",
"LOUIS DREYFUS COMPANY POLSKA Sp.z o.o.",
"M & M - Trans Michał Filipczak",
"M.W.M.Sp.z o.o.; (Dragany 24B, 23 - 145 WYSOKIE, PL)",
"MAGNOLIA PLUS Sp.z o.o.SP.K",
"MAISADOUR POLSKA Sp.z o.o., Pokrzywno 3A, 61 - 315 Krzesiny - Pokrzywno - Garaszewo, Polska",
"MAKARONY POLSKIE S.A",
"MALTEUROP POLSKA Sp.z o.o.",
"MAR - POL II MARIUSZ SALA; (Łęki Szlacheckie 2a, 97 - 352 ŁĘKI SZLACHECKIE, PL)",
"MARCIN JAKÓBCZYK P.U.H.",
"Mariusz Witkowicz EMKA TRANS",
"MARTEX GROUP Sp.z o.o.",
"MAX - PLON; (Starowiejska 11, 22 - 530 MIRCZE, PL)",
"MAX DANUTA KRÓLIKOWSKA; (Hrubieszowska 37, 22 - 100 CHEŁM, PL)",
"MAXIMIR Sp.z o.o.; (Witebska 37, 85 - 778 BYDGOSZCZ, PL)",
"MAX KRÓLIKOWSKA DANUTA SPÓŁKA KOMANDYTOWA; (Hrubieszowska 37, 22 - 100 CHEŁM, PL)",
"Meat - Market Sp.z o.o.; (Żurawia 43 / 109, 00 - 680 Warszawa, PL)",
"MEGA TRADING Sp.z o.o.",
"mFOODS Sp z o.o.; (Widzewska 14 / 306, 307, 92 - 229 ŁÓDŹ, PL)",
"MG MICHAŁ GIENIEC; (Librantowska 10, 33 - 300 NOWY SĄCZ, PL)",
"Michał Derendarz ,, AGRIKO’’",
"MILAN LOGISTIC Sp.z o.o.; (Żołnierzy 9 Dywizji Piechoty 8, 35 -083 RZESZÓW, PL)",
"MIRPASZ Marek Świerżewski; (Stara Łomża Nad Rzeką 53, 18 - 400 ŁOMŻA, PL)",
"MIZGIER TOMASZ I SYNOWIE SP.Z O.O.; (Marianowo Brodowskie 20, 63-000 ŚRODA WIELKOPOLSKA,PL)",
"MODERNFEED SP.Z O.O.; (MAGNUSZOWICE 77, 49 - 156 MAGNUSZOWICE, PL)",
"MORSKI TERMINAL ZBOŻOWY Sp.z o.o.",
"MP TRADE Sp.z o.o.",
"MULTEKO Sp.z o.o.",
"MVP GROUP Sp.z o.o.; (Cienista 36, 05-077 WARSZAWA, PL)",
"MYROSLAV KOSOVETS HPU EXPORT - IMPORT,, HERMES’’",
"MŁYN NAD WARTĄ Sp.z o.o.",
"MŁYN OSTRÓW WLKP.Józef i Teresa Otwiaska Spółka komandytowa",
"Młyn Pogorzelec Sp.z o.o.",
"Nano TechPL sp.zo.o. 41 - 500 Chorzów, Konopnickiej 6 / 7",
"Natalia Walczyk Firma Handlowo - Usługowa",
"New Products Sp z O.O.; (1000 Lecia Państwa Polskiego 10a / 107, 15 - 111 Białystok, PL)",
"NIETEN SERWIS CELNY SPÓŁKA z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ Sp.K.ODDZIAŁ TERENOWY KORCZOWA; (Przejście Graniczne W Korczowej, 37 - 550 RADYMNO, PL)",
"NODIA Sp.z o.o.; (Dowborczyków 30 / 34, 90 -019 Łódz, PL)",
"O.P.TRADE SP.Z.O.O.; (Przemysłowa 5, 35 - 105 RZESZÓW, PL)",
"Och Bont Sp.z o.o.",
"OLEWNIK - EXPO Danuta Olewnik - Cieplińska",
"OLEWNIK - EXPO Group Sp.z o.o.",
"OLEWNIK - EXPO Sp.z o.o.",
"OLVAR SP Z.O.O.; (RĄCZYNA 56, KAŃCZUGA 37 - 220, PL)",
"OPEN TRANS PIOTR CHAŁAT; (ul.Brzezińska 133, 95-040 KOLUSZKI, PL)",
"P.G.B.Polak Piotr Polish Business Group",
"P.H.U. 'PUSTELNIK' JAROSŁAW PUSTELNIK; (Kamocinek 23, 97 - 306 GRABICA, PL)",
"P.P.H.U.JULTIM JULIA MIELCZAREK",
"P.P.H.U ADAM Młyn Potakówka M.Bochnia W.Bochnia S.C.",
"P.P.U.H.AGRO - WIP Aleksandra Tarnowska",
"P.V.I EKO Sp.z o.o.",
"PETRA EXPORT SP.Z O.O., KOLEJOWA 6, 59 - 800 Zaręba, Polska",
"Phoenix Production sp.zo.o., Cynamonowa 16, 35 - 232 Rzeszów, Polska",
"PHU TRANSAGRO KRZYSZTOF STAWIARZ",
"PHUT Sięmbida Marek",
"PHU Turexpo Danuta Biała",
"PHU Zbigniew Wojtasik; (Stefanów 7, Drużbice 97 - 403, PL)",
"PHU Zbigniew Wojtasik; (Stefanów 7, Drużbice 97 - 403, PL)",
"PIOTR CELEJ; (Piłsudskiego 115, 21 - 450 STOCZEK ŁUKOWSKI, PL)",
"Podlaskie Zakłady Zbożowe Spółka akcyjna",
"POLBILDING SP.Z O.O.SP.K.; (Kabacki Dukt 6 / 53, 02 - 798 WARSZAWA, PL)",
"POLBILDING SP ZOO SP K; (Ul.Gorzowska 2a / 2.2, 65 - 127 ZIELONA GÓRA, PL)",
"PPH KROM Barbara Krom; (Straduny, 1 - go Maja 4, 19 - 300 EŁK, PL)",
"PPHU GABIKO ROMUALD GODLIŃSKI; (BOHATERÓW WRZEŚNIA 10A, KONOPNICA 98 - 313, PL)",
"PPHU JULTIM; (Wieluńska 12a, 97 - 438 RUSIEC, PL)",
"PPHU KAMPOL KRZYSZTOF ŁUŹNIAK",
"PRIME PROTEIN TRADE Sp.z o.o.; (ul.Jana III Sobieskiego 17, Rzeszów 35-002, PL)",
"PRO - FEED KRAJEWSCY SP.Z O.O.; (Wola Zambrowska, Cicha 4, 18 - 300 ZAMBRÓW, PL)",
"PRO - FEED TOMASZ KRAJEWSKI; (Cicha 4, 18 - 300 Zambrów, PL)",
"Przedsiębiorstwo Handlowo Usługowe,, TRANS – MAR’’ Stanisław Nawrocki",
"Przedsiębiorstwo Handlowo Usługowe VENUS M.Zyga Spółka Jawna; (Marysinek 2a, 05 - 870 Błonie,PL)",
"Przedsiębiorstwo Produkcyjno Usługowo - Handlowe "SOBPOL" S.J.Sobolewscy",
"Przedsiębiorstwo Usługowo - Handlowo - Transportowe ANIMEX Leszek i Anna Dzierzęccy Spółka",
"Przedsiębiorstwo Wielobranżowe AGSOL Spółka Jawna Zdzisław Wróbel i Agnieszka Wielgus",
"Przedsiębiorstwo Wielobranżowe Jan Węcławik",
"PUH Chemirol Sp.z o.o.",
"QUATRO INTERNATIONAL Sp.z o.o.",
"R.I.K.SP.Z O.O.; (Nowogrodzka 31, 00 - 511 WARSZAWA, PL)",
"RAFAŁEK HENRYK PŁOŃSKI MŁYN HANDLOWO - USŁUGOWY; (Pułazie Świerże 21, 18 - 210 SZEPIETOWO, PL)",
"RATBET PPHU; (Gostyńska 20, 63 - 860 POGORZELA, PL)",
"REGAL Usługi Transportowe Alicja Reguła; (Braciejowa 1D, 39 - 208 Gumniska, PL)",
"RKSS Sp.z o.o.; (Tczyca 145, 32 - 250 TCZYCA, PL)",
"ROL - MIX PHU Jacek Skrodzki; (Kownacin 2, 18 - 507 GRABOWO, PL)",
"ROL - TRANS ROBERT CZYŻEWSKI",
"ROLPEX Sp.z o.o.Sp.K",
"S - GROUP SP.Z O.O.; (M.Kolbe 4 - 6, 97 - 500 RADOMSKO, PL)",
"SAFE AGRO SP.Z O.O., RÓŻANA 10 / 29, 20 - 538 Lublin, Polska",
"SETTI Sp.zo.o.; (Józefitów 3 / 2, 30 -039 KRAKÓW, PL)",
"SIMBA BABY Sp.z o.o.",
"Składy drzewne II S.C.Export - Import",
"SMARTLOGISTIC Aleksandra Jaskorzyńska - Bogacz; (Władysława Łokietka 8 / 26, 97 - 500 RADOMSKO,PL)",
"SMATFOOD Sp.0.0; (Ul.szkolna 12a, 59 - 160 RADWANICE, PL)",
"Soufflet Negoce",
"SPORT - FISHING WERONIKA BUKOJEMSKA; (Sierakowskiego 10 / 1, 37 - 700 PRZEMYŚL, PL)",
"Spółdzielnia Pracy Handlowo - Produkcyjna 'Samopomoc Chłopska Pług' Mieszalnia Pasz; (Towarowa 4, 36 - 100 KOLBUSZOWA, PL)",
"STACJA LHS MAGELIT Sp.z o.o.; (Knapy 190, 39 - 450 Wola Baranowska, PL)",
"STREET RETAIL SP.Z O.O.; (PRZEMYSŁOWA 9B, KNURÓW 44 - 190, PL)",
"SUN OIL SP.Z O.O.; (AL.MICKIEWICZA ADAMA 59, KRAKÓW 31 - 120, PL)",
"SUPER - CZAD Sp.z o.o.",
"SZUDROWICZ MACIEJ GOSPODARSTWO ROLNE; (Tłukawy 11, 64 - 630 RYCZYWÓŁ, PL)",
"SŁODOWNIA SOUFFLET POLSKA Sp.z o.o.",
"Sławomir Olak W.P.H. ,, Agrahurt’’ Export - Import",
"TAVRIYA AGRO BIO INVEST SP.ZO.O.; (Rolna 191 / 193, 02 - 729 WARSZAWA, PL)",
"TEMPLATE FACTORY SP.ZO.O.; (Ul.T.Chalubińskiego 9 / 2, 02-004 WARSZAWA, PL)",
"THEGRA POLAND SP.Z O.O.; (Żelazna 59, 00 - 848 WARSZAWA, PL)",
"TIMAGRA SP.Z O.O.; (Karola Olszewskiego 6, 25 - 663 KIELCE, PL)",
"TITAN TRADE VIKTORIIA LYASHCHUK; (Wincentego Pola 18, 35-021 RZESZÓW, PL)",
"TKM OLEG WILCZYŃSKI",
"TOMY M & M Sp.z o.o.",
"Trade & amp; Trans Expert Czaicki i Czaicki Sp.Jawna; (Dębowa Góra 29, 41 - 260 SŁAWKÓW, PL)",
"TRADE AGRO UNION SA; (Talacker 50, ZURICH 8001, CH)",
"TRADE OIL SP.Z O.O.; (Ul.tomasza Zana 11a, 20 - 601 LUBLIN, PL)",
"TRANS - POL POLSKA SP.Z O.O.; (Osiedle 40 - lecia PRL 16, 64 - 630 RYCZYWÓŁ, PL)",
"TUKAN s.c.Janusz Hady, Anna Hady",
"UAB BALTIJOS JAVAI",
"UKR - ROL KOLESNYK S.K.A; (Siedmiogrodzka 1 / 115, WARSZAWA 01 - 204, PL)",
"UNITED PETFOOD POLSKA SP.Z O.O.; (Południowa 6, 63 - 460 BISKUPICE OŁOBOCZNE, PL)",
"UP TRADING Sp.z o.o.; (Ul.Bosaków 5a / 87a, 31 - 476 KRAKÓW, PL)",
"Usługi ładowarką Danuta Rozwałka",
"VAMAPOL Sp.z o.o.",
"VED OIL AGRO IGOR VEDMEDENKO; (Smoszew, Gajowa 2, 63 - 714 KOBIERNO, PL)",
"VEKTOR SBB Sp.z o.o.",
"VELES AGRO Sp.z o.o.",
"VERNUS SP.Z O.O.; (Partyzancka 60, 95 - 200 PABIANICE, PL)",
"VITERRA POLSKA Sp.z o.o.; (Cypriana Kamila Norwida 2, 80 - 280 GDAŃSK, PL)",
"Volyn Grouo Warszawa",
"W.KROM Sp.z o.o.Sp.komandyt.; (Tadeusza Kościuszki 43, 05 - 270 MARKI, PL)",
"WELTSAMEN Łukasz Gaworski Firma Handlowa; (Posmykowizna 55, 98 - 355 DZIAŁOSZYN, PL)",
"WILHELM LANDBERG Sp.z o.o.",
"WIPASZ S.A.; (Wadąg 9, 10 - 373 OLSZTYN, PL)",
"WIST SP.Z O.O.; (Wojciechowskiego 54 / 18, 02 - 495 WARSZAWA, PL)",
"WS - TRADE PLUS Sp.z o.o., Sp.K.",
"YUKON TRANSIT SP.Z O.O.; (Aleja 29 Listopada 130 / 421, 31 - 406 KRAKÓW, PL)",
"Zakład Pracy Chronionej Zakład Stolarski Wiesław Tański",
"Zakłady Zbożowe Ocieka Tuszyma Sp.z o.o.",
"ZIEMPOL WŁODZIMIERZ ŁĘTOWSKI P.H.U.; (Przechodnia 40, 18 - 200 WYSOKIE MAZOWIECKIE, PL)",
"Zioła Nałęczowskie Sp.z o.o.",
"ZŁOTE ZIARNO Sp.z o.o.; (Wspólna 70, 00 - 687 WARSZAWA, PL)",
]

export default lists
